//defines.h

#define SETBIT(WORD, BITPOS)			(WORD|=((u32)1<<BITPOS))
#define CLRBIT(WORD, BITPOS)  		(WORD&=(~(((u32)1<<BITPOS))))
#define CPLBIT(WORD, BITPOS)  		(WORD^=((u32)1<<BITPOS))


#define READBIT(WORD, BITPOS)		 	((WORD>>BITPOS)&(u32)1)
#define WRITEBIT(WORD, BITPOS, BITLEVEL)		(WORD=(WORD&(~((u32)1<<BITPOS)))|((u32)BITLEVEL<<BITPOS))
#define READWRITEBIT(WORD, DBIT, SBIT) \
(WORD=((WORD&(~((u32)1<<DBIT)))|(((WORD>>SBIT)&(u32)1)<<DBIT)))
#define READWRITE2(DWORD, DBIT, SWORD, SBIT) \
(DWORD= ((DWORD&(~((u32)1<<DBIT))) | (((SWORD>>SBIT)&(u32)1)<<DBIT)))

#define READNIBBLE(WORD, STARTBITPOS)		((WORD>>STARTBITPOS)&(u32)15)
#define WRITENIBBLE(WORD, STARTBITPOS, NIBBLEVAL) \
(WORD=((WORD&(~((u32)15<<STARTBITPOS)))|(NIBBLEVAL<<STARTBITPOS)))
#define READBYTE(WORD, STARTBITPOS) 	((WORD>>STARTBITPOS)&(u32)255)
#define WRITEBYTE(WORD, STARTBITPOS, BYTEVAL) \
(WORD=((WORD&(~((u32)255<<STARTBITPOS)))|(BYTEVAL<<STARTBITPOS)))
